// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QcMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QcMessages {

  /// <summary>Holder for reflection information generated from QcMessage.proto</summary>
  public static partial class QcMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for QcMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QcMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9RY01lc3NhZ2UucHJvdG8SClFjTWVzc2FnZXMaJ1FjU2Vuc29yTWVzc2Fn",
            "ZXMvUWNTZW5zb3JNZXNzYWdlcy5wcm90byLQAwoNU2Vuc29yTWVzc2FnZRIT",
            "CgtwYWNrZXRfbmFtZRgBIAEoCRIPCgdub2RlX2lkGAIgASgJEhIKCmdhdGV3",
            "YXlfaWQYAyABKAkSEQoJdW5peF90aW1lGAQgASgNEhMKC21pY3Jvc2Vjb25k",
            "GAUgASgFEhMKC2Vycl9jb21tZW50GAYgASgJEgsKA3ZlchgHIAEoCRImCgxh",
            "ZVNlbnNvckRhdGEY6QcgASgLMg0uQWVTZW5zb3JEYXRhSAASLAoPYWVNZWFz",
            "dXJlQ29uZmlnGOoHIAEoCzIQLkFlTWVhc3VyZUNvbmZpZ0gAEigKDWFlTGV2",
            "ZWxDb25maWcY6wcgASgLMg4uQWVMZXZlbENvbmZpZ0gAEioKDmFlVGltaW5n",
            "Q29uZmlnGOwHIAEoCzIPLkFlVGltaW5nQ29uZmlnSAASMAoRYWVTZW5zb3JM",
            "ZXZlbERhdGEY7QcgASgLMhIuQWVTZW5zb3JMZXZlbERhdGFIABIqCg5zeXN0",
            "ZW1Gd1VwZGF0ZRjuByABKAsyDy5TeXN0ZW1Gd1VwZGF0ZUgAEioKDmlvdERl",
            "dmljZVN0YXRlGO8HIAEoCzIPLklvdERldmljZVN0YXRlSABCBQoDbXNnQiUK",
            "FWNvbS5xYy5zZW5zb3JtZXNzYWdlc1oMLjtRY01lc3NhZ2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::QcSensorMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QcMessages.SensorMessage), global::QcMessages.SensorMessage.Parser, new[]{ "PacketName", "NodeId", "GatewayId", "UnixTime", "Microsecond", "ErrComment", "Ver", "AeSensorData", "AeMeasureConfig", "AeLevelConfig", "AeTimingConfig", "AeSensorLevelData", "SystemFwUpdate", "IotDeviceState" }, new[]{ "Msg" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SensorMessage : pb::IMessage<SensorMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SensorMessage> _parser = new pb::MessageParser<SensorMessage>(() => new SensorMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SensorMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QcMessages.QcMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SensorMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SensorMessage(SensorMessage other) : this() {
      packetName_ = other.packetName_;
      nodeId_ = other.nodeId_;
      gatewayId_ = other.gatewayId_;
      unixTime_ = other.unixTime_;
      microsecond_ = other.microsecond_;
      errComment_ = other.errComment_;
      ver_ = other.ver_;
      switch (other.MsgCase) {
        case MsgOneofCase.AeSensorData:
          AeSensorData = other.AeSensorData.Clone();
          break;
        case MsgOneofCase.AeMeasureConfig:
          AeMeasureConfig = other.AeMeasureConfig.Clone();
          break;
        case MsgOneofCase.AeLevelConfig:
          AeLevelConfig = other.AeLevelConfig.Clone();
          break;
        case MsgOneofCase.AeTimingConfig:
          AeTimingConfig = other.AeTimingConfig.Clone();
          break;
        case MsgOneofCase.AeSensorLevelData:
          AeSensorLevelData = other.AeSensorLevelData.Clone();
          break;
        case MsgOneofCase.SystemFwUpdate:
          SystemFwUpdate = other.SystemFwUpdate.Clone();
          break;
        case MsgOneofCase.IotDeviceState:
          IotDeviceState = other.IotDeviceState.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SensorMessage Clone() {
      return new SensorMessage(this);
    }

    /// <summary>Field number for the "packet_name" field.</summary>
    public const int PacketNameFieldNumber = 1;
    private string packetName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PacketName {
      get { return packetName_; }
      set {
        packetName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "node_id" field.</summary>
    public const int NodeIdFieldNumber = 2;
    private string nodeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NodeId {
      get { return nodeId_; }
      set {
        nodeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gateway_id" field.</summary>
    public const int GatewayIdFieldNumber = 3;
    private string gatewayId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GatewayId {
      get { return gatewayId_; }
      set {
        gatewayId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unix_time" field.</summary>
    public const int UnixTimeFieldNumber = 4;
    private uint unixTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UnixTime {
      get { return unixTime_; }
      set {
        unixTime_ = value;
      }
    }

    /// <summary>Field number for the "microsecond" field.</summary>
    public const int MicrosecondFieldNumber = 5;
    private int microsecond_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Microsecond {
      get { return microsecond_; }
      set {
        microsecond_ = value;
      }
    }

    /// <summary>Field number for the "err_comment" field.</summary>
    public const int ErrCommentFieldNumber = 6;
    private string errComment_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrComment {
      get { return errComment_; }
      set {
        errComment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ver" field.</summary>
    public const int VerFieldNumber = 7;
    private string ver_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ver {
      get { return ver_; }
      set {
        ver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "aeSensorData" field.</summary>
    public const int AeSensorDataFieldNumber = 1001;
    /// <summary>
    /// 声发射数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AeSensorData AeSensorData {
      get { return msgCase_ == MsgOneofCase.AeSensorData ? (global::AeSensorData) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AeSensorData;
      }
    }

    /// <summary>Field number for the "aeMeasureConfig" field.</summary>
    public const int AeMeasureConfigFieldNumber = 1002;
    /// <summary>
    /// 声发射采集配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AeMeasureConfig AeMeasureConfig {
      get { return msgCase_ == MsgOneofCase.AeMeasureConfig ? (global::AeMeasureConfig) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AeMeasureConfig;
      }
    }

    /// <summary>Field number for the "aeLevelConfig" field.</summary>
    public const int AeLevelConfigFieldNumber = 1003;
    /// <summary>
    /// 声发射评级配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AeLevelConfig AeLevelConfig {
      get { return msgCase_ == MsgOneofCase.AeLevelConfig ? (global::AeLevelConfig) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AeLevelConfig;
      }
    }

    /// <summary>Field number for the "aeTimingConfig" field.</summary>
    public const int AeTimingConfigFieldNumber = 1004;
    /// <summary>
    /// 声发射定时配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AeTimingConfig AeTimingConfig {
      get { return msgCase_ == MsgOneofCase.AeTimingConfig ? (global::AeTimingConfig) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AeTimingConfig;
      }
    }

    /// <summary>Field number for the "aeSensorLevelData" field.</summary>
    public const int AeSensorLevelDataFieldNumber = 1005;
    /// <summary>
    /// 声发射评级数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AeSensorLevelData AeSensorLevelData {
      get { return msgCase_ == MsgOneofCase.AeSensorLevelData ? (global::AeSensorLevelData) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AeSensorLevelData;
      }
    }

    /// <summary>Field number for the "systemFwUpdate" field.</summary>
    public const int SystemFwUpdateFieldNumber = 1006;
    /// <summary>
    /// 系统固件升级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SystemFwUpdate SystemFwUpdate {
      get { return msgCase_ == MsgOneofCase.SystemFwUpdate ? (global::SystemFwUpdate) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SystemFwUpdate;
      }
    }

    /// <summary>Field number for the "iotDeviceState" field.</summary>
    public const int IotDeviceStateFieldNumber = 1007;
    /// <summary>
    /// IOT设备状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::IotDeviceState IotDeviceState {
      get { return msgCase_ == MsgOneofCase.IotDeviceState ? (global::IotDeviceState) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.IotDeviceState;
      }
    }

    private object msg_;
    /// <summary>Enum of possible cases for the "msg" oneof.</summary>
    public enum MsgOneofCase {
      None = 0,
      AeSensorData = 1001,
      AeMeasureConfig = 1002,
      AeLevelConfig = 1003,
      AeTimingConfig = 1004,
      AeSensorLevelData = 1005,
      SystemFwUpdate = 1006,
      IotDeviceState = 1007,
    }
    private MsgOneofCase msgCase_ = MsgOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgOneofCase MsgCase {
      get { return msgCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMsg() {
      msgCase_ = MsgOneofCase.None;
      msg_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SensorMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SensorMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PacketName != other.PacketName) return false;
      if (NodeId != other.NodeId) return false;
      if (GatewayId != other.GatewayId) return false;
      if (UnixTime != other.UnixTime) return false;
      if (Microsecond != other.Microsecond) return false;
      if (ErrComment != other.ErrComment) return false;
      if (Ver != other.Ver) return false;
      if (!object.Equals(AeSensorData, other.AeSensorData)) return false;
      if (!object.Equals(AeMeasureConfig, other.AeMeasureConfig)) return false;
      if (!object.Equals(AeLevelConfig, other.AeLevelConfig)) return false;
      if (!object.Equals(AeTimingConfig, other.AeTimingConfig)) return false;
      if (!object.Equals(AeSensorLevelData, other.AeSensorLevelData)) return false;
      if (!object.Equals(SystemFwUpdate, other.SystemFwUpdate)) return false;
      if (!object.Equals(IotDeviceState, other.IotDeviceState)) return false;
      if (MsgCase != other.MsgCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PacketName.Length != 0) hash ^= PacketName.GetHashCode();
      if (NodeId.Length != 0) hash ^= NodeId.GetHashCode();
      if (GatewayId.Length != 0) hash ^= GatewayId.GetHashCode();
      if (UnixTime != 0) hash ^= UnixTime.GetHashCode();
      if (Microsecond != 0) hash ^= Microsecond.GetHashCode();
      if (ErrComment.Length != 0) hash ^= ErrComment.GetHashCode();
      if (Ver.Length != 0) hash ^= Ver.GetHashCode();
      if (msgCase_ == MsgOneofCase.AeSensorData) hash ^= AeSensorData.GetHashCode();
      if (msgCase_ == MsgOneofCase.AeMeasureConfig) hash ^= AeMeasureConfig.GetHashCode();
      if (msgCase_ == MsgOneofCase.AeLevelConfig) hash ^= AeLevelConfig.GetHashCode();
      if (msgCase_ == MsgOneofCase.AeTimingConfig) hash ^= AeTimingConfig.GetHashCode();
      if (msgCase_ == MsgOneofCase.AeSensorLevelData) hash ^= AeSensorLevelData.GetHashCode();
      if (msgCase_ == MsgOneofCase.SystemFwUpdate) hash ^= SystemFwUpdate.GetHashCode();
      if (msgCase_ == MsgOneofCase.IotDeviceState) hash ^= IotDeviceState.GetHashCode();
      hash ^= (int) msgCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PacketName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PacketName);
      }
      if (NodeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NodeId);
      }
      if (GatewayId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GatewayId);
      }
      if (UnixTime != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(UnixTime);
      }
      if (Microsecond != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Microsecond);
      }
      if (ErrComment.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ErrComment);
      }
      if (Ver.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Ver);
      }
      if (msgCase_ == MsgOneofCase.AeSensorData) {
        output.WriteRawTag(202, 62);
        output.WriteMessage(AeSensorData);
      }
      if (msgCase_ == MsgOneofCase.AeMeasureConfig) {
        output.WriteRawTag(210, 62);
        output.WriteMessage(AeMeasureConfig);
      }
      if (msgCase_ == MsgOneofCase.AeLevelConfig) {
        output.WriteRawTag(218, 62);
        output.WriteMessage(AeLevelConfig);
      }
      if (msgCase_ == MsgOneofCase.AeTimingConfig) {
        output.WriteRawTag(226, 62);
        output.WriteMessage(AeTimingConfig);
      }
      if (msgCase_ == MsgOneofCase.AeSensorLevelData) {
        output.WriteRawTag(234, 62);
        output.WriteMessage(AeSensorLevelData);
      }
      if (msgCase_ == MsgOneofCase.SystemFwUpdate) {
        output.WriteRawTag(242, 62);
        output.WriteMessage(SystemFwUpdate);
      }
      if (msgCase_ == MsgOneofCase.IotDeviceState) {
        output.WriteRawTag(250, 62);
        output.WriteMessage(IotDeviceState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PacketName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PacketName);
      }
      if (NodeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NodeId);
      }
      if (GatewayId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GatewayId);
      }
      if (UnixTime != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(UnixTime);
      }
      if (Microsecond != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Microsecond);
      }
      if (ErrComment.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ErrComment);
      }
      if (Ver.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Ver);
      }
      if (msgCase_ == MsgOneofCase.AeSensorData) {
        output.WriteRawTag(202, 62);
        output.WriteMessage(AeSensorData);
      }
      if (msgCase_ == MsgOneofCase.AeMeasureConfig) {
        output.WriteRawTag(210, 62);
        output.WriteMessage(AeMeasureConfig);
      }
      if (msgCase_ == MsgOneofCase.AeLevelConfig) {
        output.WriteRawTag(218, 62);
        output.WriteMessage(AeLevelConfig);
      }
      if (msgCase_ == MsgOneofCase.AeTimingConfig) {
        output.WriteRawTag(226, 62);
        output.WriteMessage(AeTimingConfig);
      }
      if (msgCase_ == MsgOneofCase.AeSensorLevelData) {
        output.WriteRawTag(234, 62);
        output.WriteMessage(AeSensorLevelData);
      }
      if (msgCase_ == MsgOneofCase.SystemFwUpdate) {
        output.WriteRawTag(242, 62);
        output.WriteMessage(SystemFwUpdate);
      }
      if (msgCase_ == MsgOneofCase.IotDeviceState) {
        output.WriteRawTag(250, 62);
        output.WriteMessage(IotDeviceState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PacketName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PacketName);
      }
      if (NodeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NodeId);
      }
      if (GatewayId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GatewayId);
      }
      if (UnixTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnixTime);
      }
      if (Microsecond != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Microsecond);
      }
      if (ErrComment.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrComment);
      }
      if (Ver.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ver);
      }
      if (msgCase_ == MsgOneofCase.AeSensorData) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AeSensorData);
      }
      if (msgCase_ == MsgOneofCase.AeMeasureConfig) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AeMeasureConfig);
      }
      if (msgCase_ == MsgOneofCase.AeLevelConfig) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AeLevelConfig);
      }
      if (msgCase_ == MsgOneofCase.AeTimingConfig) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AeTimingConfig);
      }
      if (msgCase_ == MsgOneofCase.AeSensorLevelData) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AeSensorLevelData);
      }
      if (msgCase_ == MsgOneofCase.SystemFwUpdate) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SystemFwUpdate);
      }
      if (msgCase_ == MsgOneofCase.IotDeviceState) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(IotDeviceState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SensorMessage other) {
      if (other == null) {
        return;
      }
      if (other.PacketName.Length != 0) {
        PacketName = other.PacketName;
      }
      if (other.NodeId.Length != 0) {
        NodeId = other.NodeId;
      }
      if (other.GatewayId.Length != 0) {
        GatewayId = other.GatewayId;
      }
      if (other.UnixTime != 0) {
        UnixTime = other.UnixTime;
      }
      if (other.Microsecond != 0) {
        Microsecond = other.Microsecond;
      }
      if (other.ErrComment.Length != 0) {
        ErrComment = other.ErrComment;
      }
      if (other.Ver.Length != 0) {
        Ver = other.Ver;
      }
      switch (other.MsgCase) {
        case MsgOneofCase.AeSensorData:
          if (AeSensorData == null) {
            AeSensorData = new global::AeSensorData();
          }
          AeSensorData.MergeFrom(other.AeSensorData);
          break;
        case MsgOneofCase.AeMeasureConfig:
          if (AeMeasureConfig == null) {
            AeMeasureConfig = new global::AeMeasureConfig();
          }
          AeMeasureConfig.MergeFrom(other.AeMeasureConfig);
          break;
        case MsgOneofCase.AeLevelConfig:
          if (AeLevelConfig == null) {
            AeLevelConfig = new global::AeLevelConfig();
          }
          AeLevelConfig.MergeFrom(other.AeLevelConfig);
          break;
        case MsgOneofCase.AeTimingConfig:
          if (AeTimingConfig == null) {
            AeTimingConfig = new global::AeTimingConfig();
          }
          AeTimingConfig.MergeFrom(other.AeTimingConfig);
          break;
        case MsgOneofCase.AeSensorLevelData:
          if (AeSensorLevelData == null) {
            AeSensorLevelData = new global::AeSensorLevelData();
          }
          AeSensorLevelData.MergeFrom(other.AeSensorLevelData);
          break;
        case MsgOneofCase.SystemFwUpdate:
          if (SystemFwUpdate == null) {
            SystemFwUpdate = new global::SystemFwUpdate();
          }
          SystemFwUpdate.MergeFrom(other.SystemFwUpdate);
          break;
        case MsgOneofCase.IotDeviceState:
          if (IotDeviceState == null) {
            IotDeviceState = new global::IotDeviceState();
          }
          IotDeviceState.MergeFrom(other.IotDeviceState);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PacketName = input.ReadString();
            break;
          }
          case 18: {
            NodeId = input.ReadString();
            break;
          }
          case 26: {
            GatewayId = input.ReadString();
            break;
          }
          case 32: {
            UnixTime = input.ReadUInt32();
            break;
          }
          case 40: {
            Microsecond = input.ReadInt32();
            break;
          }
          case 50: {
            ErrComment = input.ReadString();
            break;
          }
          case 58: {
            Ver = input.ReadString();
            break;
          }
          case 8010: {
            global::AeSensorData subBuilder = new global::AeSensorData();
            if (msgCase_ == MsgOneofCase.AeSensorData) {
              subBuilder.MergeFrom(AeSensorData);
            }
            input.ReadMessage(subBuilder);
            AeSensorData = subBuilder;
            break;
          }
          case 8018: {
            global::AeMeasureConfig subBuilder = new global::AeMeasureConfig();
            if (msgCase_ == MsgOneofCase.AeMeasureConfig) {
              subBuilder.MergeFrom(AeMeasureConfig);
            }
            input.ReadMessage(subBuilder);
            AeMeasureConfig = subBuilder;
            break;
          }
          case 8026: {
            global::AeLevelConfig subBuilder = new global::AeLevelConfig();
            if (msgCase_ == MsgOneofCase.AeLevelConfig) {
              subBuilder.MergeFrom(AeLevelConfig);
            }
            input.ReadMessage(subBuilder);
            AeLevelConfig = subBuilder;
            break;
          }
          case 8034: {
            global::AeTimingConfig subBuilder = new global::AeTimingConfig();
            if (msgCase_ == MsgOneofCase.AeTimingConfig) {
              subBuilder.MergeFrom(AeTimingConfig);
            }
            input.ReadMessage(subBuilder);
            AeTimingConfig = subBuilder;
            break;
          }
          case 8042: {
            global::AeSensorLevelData subBuilder = new global::AeSensorLevelData();
            if (msgCase_ == MsgOneofCase.AeSensorLevelData) {
              subBuilder.MergeFrom(AeSensorLevelData);
            }
            input.ReadMessage(subBuilder);
            AeSensorLevelData = subBuilder;
            break;
          }
          case 8050: {
            global::SystemFwUpdate subBuilder = new global::SystemFwUpdate();
            if (msgCase_ == MsgOneofCase.SystemFwUpdate) {
              subBuilder.MergeFrom(SystemFwUpdate);
            }
            input.ReadMessage(subBuilder);
            SystemFwUpdate = subBuilder;
            break;
          }
          case 8058: {
            global::IotDeviceState subBuilder = new global::IotDeviceState();
            if (msgCase_ == MsgOneofCase.IotDeviceState) {
              subBuilder.MergeFrom(IotDeviceState);
            }
            input.ReadMessage(subBuilder);
            IotDeviceState = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PacketName = input.ReadString();
            break;
          }
          case 18: {
            NodeId = input.ReadString();
            break;
          }
          case 26: {
            GatewayId = input.ReadString();
            break;
          }
          case 32: {
            UnixTime = input.ReadUInt32();
            break;
          }
          case 40: {
            Microsecond = input.ReadInt32();
            break;
          }
          case 50: {
            ErrComment = input.ReadString();
            break;
          }
          case 58: {
            Ver = input.ReadString();
            break;
          }
          case 8010: {
            global::AeSensorData subBuilder = new global::AeSensorData();
            if (msgCase_ == MsgOneofCase.AeSensorData) {
              subBuilder.MergeFrom(AeSensorData);
            }
            input.ReadMessage(subBuilder);
            AeSensorData = subBuilder;
            break;
          }
          case 8018: {
            global::AeMeasureConfig subBuilder = new global::AeMeasureConfig();
            if (msgCase_ == MsgOneofCase.AeMeasureConfig) {
              subBuilder.MergeFrom(AeMeasureConfig);
            }
            input.ReadMessage(subBuilder);
            AeMeasureConfig = subBuilder;
            break;
          }
          case 8026: {
            global::AeLevelConfig subBuilder = new global::AeLevelConfig();
            if (msgCase_ == MsgOneofCase.AeLevelConfig) {
              subBuilder.MergeFrom(AeLevelConfig);
            }
            input.ReadMessage(subBuilder);
            AeLevelConfig = subBuilder;
            break;
          }
          case 8034: {
            global::AeTimingConfig subBuilder = new global::AeTimingConfig();
            if (msgCase_ == MsgOneofCase.AeTimingConfig) {
              subBuilder.MergeFrom(AeTimingConfig);
            }
            input.ReadMessage(subBuilder);
            AeTimingConfig = subBuilder;
            break;
          }
          case 8042: {
            global::AeSensorLevelData subBuilder = new global::AeSensorLevelData();
            if (msgCase_ == MsgOneofCase.AeSensorLevelData) {
              subBuilder.MergeFrom(AeSensorLevelData);
            }
            input.ReadMessage(subBuilder);
            AeSensorLevelData = subBuilder;
            break;
          }
          case 8050: {
            global::SystemFwUpdate subBuilder = new global::SystemFwUpdate();
            if (msgCase_ == MsgOneofCase.SystemFwUpdate) {
              subBuilder.MergeFrom(SystemFwUpdate);
            }
            input.ReadMessage(subBuilder);
            SystemFwUpdate = subBuilder;
            break;
          }
          case 8058: {
            global::IotDeviceState subBuilder = new global::IotDeviceState();
            if (msgCase_ == MsgOneofCase.IotDeviceState) {
              subBuilder.MergeFrom(IotDeviceState);
            }
            input.ReadMessage(subBuilder);
            IotDeviceState = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
