// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBWebApp.Models;

#nullable disable

namespace NBWebApp.Migrations
{
    [DbContext(typeof(NBDataContext))]
    [Migration("20231212052407_InitalClass")]
    partial class InitalClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NBWebApp.Models.AeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("AMP")
                        .HasColumnType("double")
                        .HasColumnName("amp");

                    b.Property<double>("ASL")
                        .HasColumnType("double")
                        .HasColumnName("asl");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("deviceid");

                    b.Property<int>("DuringTime")
                        .HasColumnType("int")
                        .HasColumnName("duringtime");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inserttime");

                    b.Property<double>("Power")
                        .HasColumnType("double")
                        .HasColumnName("power");

                    b.Property<double>("RMS")
                        .HasColumnType("double")
                        .HasColumnName("rms");

                    b.Property<int>("RingingNum")
                        .HasColumnType("int")
                        .HasColumnName("ringingnum");

                    b.Property<int>("RisingNum")
                        .HasColumnType("int")
                        .HasColumnName("risingnum");

                    b.Property<int>("RisingTime")
                        .HasColumnType("int")
                        .HasColumnName("risingtime");

                    b.Property<string>("SN")
                        .HasColumnType("longtext")
                        .HasColumnName("sn");

                    b.Property<double>("UnixTime")
                        .HasColumnType("double")
                        .HasColumnName("unixtime");

                    b.HasKey("Id");

                    b.ToTable("aedatas", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.AeRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("LevelConfig")
                        .HasColumnType("longtext")
                        .HasColumnName("levelconfig");

                    b.Property<string>("MeasureConfig")
                        .HasColumnType("longtext")
                        .HasColumnName("measureconfig");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("TimingConfig")
                        .HasColumnType("longtext")
                        .HasColumnName("timingconfig");

                    b.HasKey("Id");

                    b.ToTable("aerules", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.AeWaveData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("data");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("deviceid");

                    b.Property<double>("Enlarge")
                        .HasColumnType("double")
                        .HasColumnName("enlarge");

                    b.Property<int>("Gain")
                        .HasColumnType("int")
                        .HasColumnName("gain");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inserttime");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("SN")
                        .HasColumnType("longtext")
                        .HasColumnName("sn");

                    b.Property<int>("Speed")
                        .HasColumnType("int")
                        .HasColumnName("speed");

                    b.Property<double>("UnixTime")
                        .HasColumnType("double")
                        .HasColumnName("unixtime");

                    b.HasKey("Id");

                    b.ToTable("aewavedatas", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.AlarmData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("deviceid");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<bool>("Settle")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("settle");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("time");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("alarmdatas", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.AlarmRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Max")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("max");

                    b.Property<decimal>("Min")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("min");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("alarmrules", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.CommDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("IP")
                        .HasColumnType("longtext")
                        .HasColumnName("ip");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("ProductLineId")
                        .HasColumnType("int")
                        .HasColumnName("productlineid");

                    b.Property<string>("SN")
                        .HasColumnType("longtext")
                        .HasColumnName("sn");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("commdevices", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Address")
                        .HasColumnType("int")
                        .HasColumnName("address");

                    b.Property<int?>("AeRuleId")
                        .HasColumnType("int")
                        .HasColumnName("aeruleid");

                    b.Property<int?>("AlarmRuleId")
                        .HasColumnType("int")
                        .HasColumnName("alarmruleid");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("channel");

                    b.Property<int>("CommDeviceId")
                        .HasColumnType("int")
                        .HasColumnName("commdeviceid");

                    b.Property<int?>("GatherRuleId")
                        .HasColumnType("int")
                        .HasColumnName("gatherruleid");

                    b.Property<decimal>("MaxSignal")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("maxsignal");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("maxvalue");

                    b.Property<decimal>("MinSignal")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("minsignal");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("minvalue");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("Pos")
                        .HasColumnType("int")
                        .HasColumnName("pos");

                    b.Property<int>("ProductLineId")
                        .HasColumnType("int")
                        .HasColumnName("productlineid");

                    b.Property<string>("SN")
                        .HasColumnType("longtext")
                        .HasColumnName("sn");

                    b.Property<int>("Samping")
                        .HasColumnType("int")
                        .HasColumnName("samping");

                    b.Property<int>("SignalTypeId")
                        .HasColumnType("int")
                        .HasColumnName("signaltypeid");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.GatherRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("endtime");

                    b.Property<int>("Interval")
                        .HasColumnType("int")
                        .HasColumnName("interval");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starttime");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("gatherrules", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.ProductLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("longtext")
                        .HasColumnName("image");

                    b.Property<DateTime?>("InstallTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("installtime");

                    b.Property<string>("Level")
                        .HasColumnType("longtext")
                        .HasColumnName("level");

                    b.Property<string>("Life")
                        .HasColumnType("longtext")
                        .HasColumnName("life");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("productlines", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.SensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CommDeviceId")
                        .HasColumnType("int")
                        .HasColumnName("commdeviceid");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("data");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.ToTable("sensordatas", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.SignalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("maxvalue");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("minvalue");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("signaltypes", (string)null);
                });

            modelBuilder.Entity("NBWebApp.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("userinfos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin",
                            Password = "E10ADC3949BA59ABBE56E057F20F883E",
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
